BEGIN;
ALTER TABLE games ADD COLUMN IF NOT EXISTS rules_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE games ADD COLUMN IF NOT EXISTS is_test BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE games ADD COLUMN IF NOT EXISTS fast_track_world JSONB NOT NULL DEFAULT '{}';
ALTER TABLE game_players ADD COLUMN IF NOT EXISTS dream_cell_index INTEGER;
ALTER TABLE player_financial_state ADD COLUMN IF NOT EXISTS fast_track_start_income_cents BIGINT NOT NULL DEFAULT 0;
ALTER TABLE player_financial_state ADD COLUMN IF NOT EXISTS fast_track_income_cents BIGINT NOT NULL DEFAULT 0;
ALTER TABLE player_financial_state ADD COLUMN IF NOT EXISTS fast_track_charity BOOLEAN NOT NULL DEFAULT false;
COMMIT;
